baseURL = "https://noobieta-profile.github.io/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "My Profile"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "ğŸ˜copyrightğŸ¤“"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Noobieta"
        tagline = "âœŒğŸ˜‚ DevkolektorâœŒğŸ¤“"
        location = "ğŸ¡Tangerang CityğŸ¡"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "#"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "#"
            title = "Orcid"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "#"
            title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Tamvan,  baik hati dan tidak sombong! Kebanyakan kurang beruntung mulu ğŸ˜–"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Freelance & Teknisi"
            dates = "2021 - *Present*"
            company = "C.I.A"
            details = "Printed from desktop. Sent [emails](#)."
        [[params.experience.list]]
            position = "Pengajar Sukwan- Produktif"
            dates = "2020-2021"
            url = "#"
            company = "SMK AL-Madani"
            details = "Jl. Raya Cadas Kp. Sondol Kab.Tangerang"
        [[params.experience.list]]
            position = "Pengajar Sukwan-Produktif"
            dates = "2014 - 2017"
            url = "#"
            company = "SMK Citra Madani"
            details = "Jl. Raya Daon Kab.Tangerang"
        [[params.experience.list]]
            position = "Pengajar Sukwan-Produktif"
            dates = "2016-2018"
            url = "#"
            company = "SMK Anak Bangsa"
            details = "Jl. Raya Daon Jawaringan Kab.Tangerang"
        [[params.experience.list]]
            position = "ROOM BOY"
            dates = "2013-2014"
            url = "#"
            company = "Hotel SandiLa"
            details = "Jl. Geger Kalong Hilir No. 145 kab. Bandung"
        [[params.experience.list]]
            position = "Operator"
            dates = "2013-2014"
            url = "#"
            company = "CAR WASH PD. MITRA"
            details = "Jl. Geger Kalong Hilir No. 139 kab. Bandung"
        [[params.experience.list]]
            position = "Pengajar Sukwan-PJOK"
            dates = "2011-2012"
            url = "#"
            company = "SMP AL-Falah"
            details = "Jl. Dago kab. Bandung"
        [[params.experience.list]]
            position = "Operator"
            dates = "2009-2010"
            url = "#"
            company = "WARNET C.I.A"
            details = "Jl.Kosambi kab. Bandung"
       [[params.experience.list]]
           position = "Coach Futsal"
           dates = "2007-2008"
           url = "#"
           company = "SMP Negeri 48 Bandung"
           details = "Ciwastra kab. Bandung"
    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "SD"
            url = "#"
            college = "SD Negeri Badak III"
            dates = "poho tahun"
        [[params.education.list]]
            degree = "SMP"
            url = "#"
            college = "SMP I Negeri Rajeg"
            dates = "poho"
        [[params.education.list]]
            degree = "SMA"
            url ="#"
            college = "SMA Negeri Cisurupan"
            dates = "2005-2006"
        [[params.education.list]]
            degree = "S1"
            url ="#"
            college = "Universitas Pendidikan Indonesia "
            dates = "2006"
            details = "Jl. Ledeng-Lembang kab. Bandung, (Failed/Telulus-lulus ğŸ˜«"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Belom bikin Buku"
            authors = "Noobieta"
            date = "2018"
            journal = "Not Found ğŸ˜ª"
            url = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Belum bikin Buku"
            authors = "Noobieta"
            date = "2018"
            journal = "Not Found"
            url = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Belum Bikin Buku"
            authors = "Noobieta"
            date = "2018"
            journal = "404 Not Found"
            url = "#"
            type = "Book"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Gagal"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Gagal lagi"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Gagal lagi"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Gagal Terus ğŸ˜ª"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"
        [[params.skill.list]]
            skill = "âœŒğŸ¤“  Hardware PC & Laptop  ğŸ˜"
            skillrating = 75
        [[params.skill.list]]
            skill = "ğŸ¤” Software & Installation ğŸ˜ª"
            skillrating = 75
        [[params.skill.list]]
            skill = "ğŸ˜« Android & flashing ğŸ˜‚"
            skillrating = 75
        [[params.skill.list]]
            skill = "ğŸ˜ª Komputer & Jaringan ğŸ˜ª"
            skillrating = 70
        [[params.skill.list]]
            skill = "ğŸ˜‚ OS Android"
            skillrating = 90
        [[params.skill.list]]
            skill = "ğŸ˜‚ OS Windows"
            skillrating = 90
        [[params.skill.list]]
            skill = "ğŸ˜ OS Linux"
            skillrating = 80
        [[params.skill.list]]
            skill = "ğŸ¤“ Office ğŸ˜…"
            skillrating = 70
        [[params.skill.list]]
            skill = "âœŒğŸ˜‚ HTML, CSS ğŸ˜‚"
            skillrating = 50
        [[params.skill.list]]
            skill = "âœŒğŸ¤“ PHP ğŸ˜‚"
            skillrating = 20
        [[params.skill.list]]
            skill = "âœŒğŸ¤“ java ğŸ˜‚"
            skillrating = 5
        [[params.skill.list]]
            skill = "âœŒğŸ¤“ Python ğŸ˜‚"
            skillrating = 5
        [[params.skill.list]]
            skill = "âœŒğŸ¤“ Photoshop ğŸ˜‚"
            skillrating = 50
    
    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Dreaming"
        [[params.hobby.list]]
            hobby = "Spaming"
        [[params.hobby.list]]
            hobby = "Gaming"
        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Maling"